test(pull-request)/Add Makefile
LaOuede/42-ft_irc pull request #1
Opened 2023-12-18 15:44 UTC by LaOuede

Little push to test pull_request functionality :)

2023-12-18 15:53 UTC, TwindZ requested changes
enlever le ircserv et repush svp

2023-12-18 17:14 UTC, Prezcoder reviewed
C’est beau!

2023-12-19 15:19 UTC, TwindZ approved these changes
Looking good for me!

2023-12-19 15:21 UTC, Prezcoder approved these changes

2023-12-19 16:32 UTC, merged